### ISSUE TITLE
Request for Config and Spec Files for Kernel 5.10, 5.15, and 6.1 on Rocky Linux 8 (including aarch64)

### ISSUE THREAD

**Issue by iwalke** [elrepo/kernel#1]
Hi, I would like to request the provision of the config and spec files for kernels 5.10, 5.15, and 6.1, specifically for Rocky Linux 8, including support for the aarch64 architecture.

After building via rpmbuild, it should be possible to generate a full list of RPM packages, similar to Rocky Linux's package set, which includes but is not limited to the following:

- kernel.x86_64
- kernel-core.x86_64
- kernel-modules.x86_64
- kernel-tools.x86_64
- kernel-tools-libs.x86_64
- kernel-debug.x86_64
- kernel-debug-core.x86_64
- kernel-debug-debuginfo.x86_64
- kernel-debug-modules.x86_64
- kernel-debuginfo.x86_64
- kernel-debuginfo-common-x86_64.x86_64
- kernel-headers.x86_64
- kernel-tools-debuginfo.x86_64

Thank you for your consideration

**Comment by pjperry** [comment]
Hi,

Due to a lack of resources, we are only able to commit to supporting two kernel sets. We have chosen that to be our mainline offering (kernel-ml), and one LTS offering (kernel-lt) which is currently the 5.4.x branch on el8. We simply do not have the resources to build and maintain multiple LTS branches (5.10, 5.15 and 6.1). If you wish these packages, if should be simply enough to fork each from the last kernel-ml spec file for each branch, and update to the latest upstream source tarball.

ELRepo does not offer debug or debuginfo kernel packages, and we have no plans to do so. It is not a simple task to build debug packages from our spec files, and again we are conscious of the resource that large debug packages would consume. If you need to debug a specific issue and Rocky provides debug packages, you may be better placed using one of their packages.

We only currently support aarch64 on el9. If you have aarch64 hardware, I would suggest running el9 where both kernel-lt-6.1 and kernel-ml-6.10 packages are available.

**Comment by iwalke** [comment]
I regret that I was unable to find the spec files for kernel-ml-5.15 and kernel-ml-5.10; I was only able to locate the spec files for kernel-ml-6.1 and kernel-lt-5.4.

Regarding the debug, debuginfo, and headers RPM packages, their use cases aren't frequent, but they are useful when needed.

As for support for aarch64 hardware, the demand is not very high, so it can be scheduled for later. However, as you mentioned using el9, that version is quite new, and its ecosystem support is still not very mature. Many systems are still on el7, so focusing on el8 is more stable and aligns with current trends.

In terms of resources, since GitHub offers free file storage, there’s no need to build RPM packages. However, I suggest storing the relevant config and spec files in a GitHub repository. There's no need to delete old config and spec files.

**Comment by pjperry** [comment]
We are now fully utilising github for our kernel specs and configs, although I note that the commit history only goes back so far.

@toracat - when kernel-ml gets updated to a new branch, would it be more convenient to fork the latest spec file (leaving the original in place) rather than renaming it? Then the last 6.5.x, 6.6.x,6.7.x etc snapshot would be readily available rather than having to trawl back through the history of commits for 6.10.latest, for example.

@toracat do we have old specs anywhere for 5.10 and 5.15 branches (from kernel-ml) that @yixiuge301 could fork as the current history in github only dates back to circa 6.5?

**Comment by tqhoang84** [comment]
@yixiuge301 - Here is an [ELRepo archive](https://linux.cc.iitk.ac.in/mirror/centos/elrepo/kernel/el8/SRPMS/) that still has the kernel-ml-5.10 and kernel-ml-5.15 SRPM's.

I strongly suggest that you validate the SRPM files before using them (e.g. rpm -K).

**Comment by iwalke** [comment]
> @yixiuge301 - Here is an [ELRepo archive](https://linux.cc.iitk.ac.in/mirror/centos/elrepo/kernel/el8/SRPMS/) that still has the kernel-ml-5.10 and kernel-ml-5.15 SRPM's.
> 
> I strongly suggest that you validate the SRPM files before using them (e.g. rpm -K).

Thank you so much

**Comment by toracat** [comment]
We will try to archive older SPEC/configs online to the extent possible.
